name: Run Tests

on:
  push:
    branches:
      - Develop
      - main
  pull_request:
    branches:
      - Develop
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Cache dependencias Maven
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven

      - name: Arrancar aplicación Spring Boot
        run: mvn spring-boot:run -Dspring-boot.run.arguments=--server.port=8080 &

      - name: Esperar a que el servidor arranque
        run: |
          for i in {1..30}; do
            if nc -z localhost 8080; then
              echo "Servidor Spring Boot arriba"
              break
            fi
            echo "Esperando Spring Boot..."
            sleep 1
          done

      - name: Ejecutar tests
        run: mvn clean test -B --fail-at-end
